=begin
#Swagger API2Cart

#API2Cart

OpenAPI spec version: 1.1
Contact: contact@api2cart.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.16

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ProductVariantAddAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductVariantAddAttributes' do
  before do
    # run before each test
    @instance = SwaggerClient::ProductVariantAddAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductVariantAddAttributes' do
    it 'should create an instance of ProductVariantAddAttributes' do
      expect(@instance).to be_instance_of(SwaggerClient::ProductVariantAddAttributes)
    end
  end
  describe 'test attribute "attribute_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "attribute_value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "attribute_price"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
